### ISSUE TITLE
有支持 ACL 的计划吗？

### ISSUE THREAD

**Issue by wzxinchen** [2881099/FreeRedis#110]
支持通过 C# 操作这些指令
https://blog.csdn.net/qq_29235677/article/details/121475204

**Comment by 2881099** [comment]
已经支持的啦，方法点不出来么

cli.AclXxx

**Comment by wzxinchen** [comment]
> 已经支持的啦，方法点不出来么
> 
> cli.AclXxx

好吧，不好意思我还没有实际使用，所以不知道。因为看文档中没提到，所以以为不支持。

棒棒的！
