### ISSUE TITLE
Skywalking Walking

### ISSUE THREAD

**Issue by wzxinchen** [2881099/FreeRedis#111]
是否支持 SKywalking？

从源码和实验结果上看好像是不支持的？

Skywalking 的 dashboard 上面没有redis服务器的IP

**Comment by 2881099** [comment]
notice 事件，自己接入

**Comment by jianxuanbing** [comment]
跪求支持

**Comment by guochen2** [comment]
> 

参照  https://github.com/SkyAPM/SkyAPM-dotnet/tree/06c60d97e930fe932fc148e40aa5031372a210c7/src/SkyApm.Diagnostics.FreeSql  这个直接写一个就可以啦

**Comment by ZUOXIANGE** [comment]
[SkyApm.Diagnostics.FreeRedis](https://github.com/SkyAPM/SkyAPM-dotnet/tree/main/src/SkyApm.Diagnostics.FreeRedis) 已经有支持了,是解析notice事件的log做的
