### ISSUE TITLE
Sentinel环境下master节点失效

### ISSUE THREAD

**Issue by victor596** [2881099/FreeRedis#116]
这种状况下FreeRedis会不会自动连接新的master节点？我目前测试的结果是没有

**Comment by 2881099** [comment]
会，只要哨兵环境配置正确

**Comment by victor596** [comment]
我再仔细测试过,   在kill -KILL <master redis pid> 后FreeRedis确实是没有发生自动切换. 抛出"由于目标计算机积极拒绝，无法连接"
sentinel配置无误 , 执行 SENTINEL get-master-addr-by-name myprimary 返回的是正确的地址,
连接此地址执行 info 也正确显示 "master" , set a a 也正常 。

**Comment by 2881099** [comment]
kill 后不会马上切换，需要短暂几秒的切换过程，我怀疑你的程序没有 try catch 以外退出了。

重点：哨兵重新选举没那么快。

**Comment by victor596** [comment]
我是打断点来测试的，在kill master的进程后执行 SENTINEL get-master-addr-by-name myprimary 得到正确的数据再继续后继操作。  当出错时SentinelAdapter.ResetSentinel() 都会执行，但之后还是返回失败的master node.

 [Fact]
        public void TestSentinel()
        {
            RedisClient csredis = new RedisClient(
                 "myprimary",
                 new[] { 
                     "192.168.2.228:26379", "192.168.2.228:26380", "192.168.2.228:26381" 
                 },
                 true 
                  );

            csredis.Set<DateTime>("sentinel:test:1", DateTime.Now);
            Assert.True(csredis.Exists("sentinel:test:1"));

            csredis.Set<DateTime>("sentinel:test:2", DateTime.Now);
            Assert.True(csredis.Exists("sentinel:test:2"));

            csredis.Set<DateTime>("sentinel:test:3", DateTime.Now);
            Assert.True(csredis.Exists("sentinel:test:3"));

            try
            {
                csredis.Set<DateTime>("sentinel:test:4", DateTime.Now);  //在此处打断点暂停，然后kill master pid ,
                Assert.True(csredis.Exists("sentinel:test:4"));          //执行  sentinel get-master-addr-by-name myprimary 看到已经切换正确的master node
            }
            catch(Exception ex) { }

            try
            {
                csredis.Set<DateTime>("sentinel:test:4", DateTime.Now);  //打断点,这里还是会出错
                Assert.True(csredis.Exists("sentinel:test:4"));
            }
            catch (Exception ex) { }

            csredis.Set<DateTime>("sentinel:test:5", DateTime.Now);  //打断点,这里还是会出错
            Assert.True(csredis.Exists("sentinel:test:5"));

        }

**Comment by 2881099** [comment]
Assert.True(csredis.Exists("sentinel:test:4"));

这行你等了多久执行的，等多几秒再执行试试。

**Comment by victor596** [comment]
>
