### ISSUE TITLE
是否考虑添加DiagnosticSource

### ISSUE THREAD

**Issue by softlgl** [2881099/FreeRedis#124]
是否考虑添加诊断日志相关，或者添加拦截器之类的，方便观测和监控命令执行相关。

**Comment by 2881099** [comment]
可以自己在 Notice 事件上加，或者在 Interpers 插件功能上加

这两个都是 FreeRedis 提供的功能

**Comment by ZUOXIANGE** [comment]
我已经加上了 #205
