### ISSUE TITLE
内容占用太高，是我使用不对吗

### ISSUE THREAD

**Issue by pershow** [2881099/FreeRedis#128]
![image](https://user-images.githubusercontent.com/11623270/216775509-6e231508-65cf-437e-b38d-45b6d56edb08.png)

**Comment by 2881099** [comment]
单例吗？不重复创建 RedisClient 对象

**Comment by pershow** [comment]
> 单例吗？不重复创建 RedisClient 对象

多个实例，多个实例订阅某一个频道

**Comment by pershow** [comment]
已解决  单例就行
