### ISSUE TITLE
在Redis7下读取Stream信息报错

### ISSUE THREAD

**Issue by 5653325** [2881099/FreeRedis#153]
操作系统Win11；
Redis版本：RedisWin 7.0.11 (04/22/2023/0) 64 bit
FreeRedis版本：1.1.3
.NET版本：4.7 WPF
`var info = App.RedisHelper.XInfoStream(_streamKey);`
报错：
![111](https://github.com/2881099/FreeRedis/assets/3361135/e68cc892-8783-49ea-9e81-e5fc377a76dd)

使用CSRedisCore也报错，只不过报错信息不同。
在Redis命令行下是可以获取到队列信息的：
![image](https://github.com/2881099/FreeRedis/assets/3361135/2a665553-9db5-4a7f-a8da-fed42e168914)

**Comment by 2881099** [comment]
v1.1.5 解决兼容好了

redis7.0 返回结果变化了，之前是按 6.0 结果解析的

**Comment by 5653325** [comment]
可以了，大佬V587。
