### ISSUE TITLE
HMSetAsync,HMSet,HSet,HSetAsync调用问题

### ISSUE THREAD

**Issue by CodingdAwn** [2881099/FreeRedis#160]
public Task HMSetAsync<T>(string key, string field, T value, params object[] fieldValues) => HSetAsync(false, key, field, value, fieldValues);

public void HMSet<T>(string key, string field, T value, params object[] fieldValues) => HSet(true, key, field, value, fieldValues);

public Task<long> HSetAsync<T>(string key, string field, T value, params object[] fieldValues) => HSetAsync(false, key, field, value, fieldValues);

public long HSet<T>(string key, string field, T value, params object[] fieldValues) => HSet(false, key, field, value, fieldValues);

源码中的定义
HMsetAsync参数使用的false即调用的实际上是HSet，而HMSet传的是true使用的HMSet，这里是不是写错了

看官方文档4.0以后HMset就被弃用了 是否这里考虑整合都调用HSet

**Comment by 2881099** [comment]
是的，HMSetAsync 参数应该传 true
