### ISSUE TITLE
SSL 连接 添加证书

### ISSUE THREAD

**Issue by li-yuelun** [2881099/FreeRedis#164]
目前库中有 sslStream 但应该没有添加证书的方法。
是否可添加如下图的方法， 谢谢

![image](https://github.com/2881099/FreeRedis/assets/56946015/0f2d96e3-f230-4269-afd0-20afe86d998c)

**Comment by 2881099** [comment]
提供代码前端，我明天看看

**Comment by li-yuelun** [comment]
我自己是在0.3.7的版本上改的 是这样实现的 

**注册**
`
  var redis = new RedisClient(
`
`
                   $"127.0.0.1:5555,password=password,defaultDatabase=11,ssl=true,retry=60000");
`
`
                    redis.Serialize = obj => JsonConvert.SerializeObject(obj);
`
`
                    redis.Deserialize = (json, type) => JsonConvert.DeserializeObject(json, type);
`
`
                    redis.userCertificateSelectionCallback += delegate
`
`
                    {
`
`
                        return SelectLocalCertificate("ca.crt");
`
`
                    };
`
`
                    redis.userCertificateValidationCallback += ValidateServerCertificate;
`
**RedisClient 更改**

> 添加属性

`
public event RemoteCertificateValidationCallback userCertificateValidationCallback;
`
`
public event LocalCertificateSelectionCallback userCertificateSelectionCallback;
`

**DefaultRedisSocket 更改**

> 添加属性

`
public event RemoteCertificateValidationCallback userCertificateValidationCallback;
`
`
public event LocalCertificateSelectionCallback userCertificateSelectionCallback;
`

> 构造函数

`
 public DefaultRedisSocket(string host, bool ssl,
            RemoteCertificateValidationCallback userCertificateValidationCallback,
            LocalCertificateSelectionCallback userCertificateSelectionCallback)
`
`
        {
`
`
            Host = host;
`
`
            Ssl = ssl;
`
`
            CertificateSelection = userCertificateSelectionCallback;
`
`
            CertificateValidation = userCertificateValidationCallback;
`
`
        }
`

然后再设置下SslStream就行了

**Comment by 2881099** [comment]
```csharp
ConnectionStringBuilder connectionString = "127.0.0.1:5555,password=password,defaultDatabase=11,ssl=true,retry=60000";
connectionString.CertificateSelection += delegate
{
    return SelectLocalCertificate("ca.crt");
};
connectionString.CertificateValidation += delegate
{
    return true;
};

var redis = new RedisClient(connectionString);
```
