### ISSUE TITLE
连接redis 2.0.6版本报错

### ISSUE THREAD

**Issue by renxuefeng** [2881099/FreeRedis#165]
redis_connection_string：192.168.*.*:6379,defaultDatabase=11
报错：【192.168.*.*:6379/11】Status unavailable, waiting for recovery. ERR wrong number of arguments

,netcore 6.0 连接报错，redis版本： 2.0.6

**Comment by 2881099** [comment]
cli.Notice += (_, e) => Console.WriteLine(e.Log);

把这个打印一下，定位错误的命令

**Comment by renxuefeng** [comment]
defaultDatabase超了
