### ISSUE TITLE
systemctl stop卡住

### ISSUE THREAD

**Issue by lizayu666** [2881099/FreeRedis#175]
Linux用FreeRedis，启动时没有与redis建立链接的情况下，用systemctl stop没有问题。但链接池有多个链接的情况下，用systemctl stop关闭程序服务就会一直卡死，一直在等待与redis链接的释放。

**Comment by lizayu666** [comment]
> Linux用FreeRedis，启动时没有与redis建立链接的情况下，用systemctl stop没有问题。但链接池有多个链接的情况下，用systemctl stop关闭程序服务就会一直卡死，一直在等待与redis链接的释放。

**Comment by 2881099** [comment]
程序退出时释放一下

**Comment by 2881099** [comment]
Dispose
