### ISSUE TITLE
连续BLPOP取值，驱动会发生FreeRedis.RedisServerException: MOVED异常

### ISSUE THREAD

**Issue by xafxy** [2881099/FreeRedis#182]
连续BLPOP取值，驱动会发生FreeRedis.RedisServerException: MOVED异常
测试异常如下图，驱动异常
![image](https://github.com/2881099/FreeRedis/assets/102198415/ac3a53f0-2519-436b-a21d-3f86648b4191)

**Comment by xafxy** [comment]
FreeRedis版本：1.2.15
.net6.0
代码：
1.连接
{
"192.168.1.162:6380,password=qwe#2023eap,connectTimeout=30000,idleTimeout=45000,receiveTimeout=30000,sendTimeout=30000,maxpoolsize=400",     "192.168.1.162:6381,password=qwe#2023eap,connectTimeout=30000,idleTimeout=45000,receiveTimeout=30000,sendTimeout=30000,maxpoolsize=400",
"192.168.1.162:6382,password=qwe#2023eap,connectTimeout=30000,idleTimeout=45000,receiveTimeout=30000,sendTimeout=30000,maxpoolsize=400",
"192.168.1.162:6383,password=qwe#2023eap,connectTimeout=30000,idleTimeout=45000,receiveTimeout=30000,sendTimeout=30000,maxpoolsize=400",
"192.168.1.162:6384,password=qwe#2023eap,connectTimeout=30000,idleTimeout=45000,receiveTimeout=30000,sendTimeout=30000,maxpoolsize=400",
"192.168.1.162:6385,password=qwe#2023eap,connectTimeout=30000,idleTimeout=45000,receiveTimeout=30000,sendTimeout=30000,maxpoolsize=400",
"192.168.1.162:6386,password=qwe#2023eap,connectTimeout=30000,idleTimeout=45000,receiveTimeout=30000,sendTimeout=30000,maxpoolsize=400",
"192.168.1.162:6387,password=qwe#2023eap,connectTimeout=30000,idleTimeout=45000,receiveTimeout=30000,sendTimeout=30000,maxpoolsize=400",
"192.168.1.162:6388,password=qwe#2023eap,connectTimeout=30000,idleTimeout=45000,receiveTimeout=30000,sendTimeout=30000,maxpoolsize=400",
 };
redisClient = new RedisClient(conStr.Select(x => ConnectionStringBuilder.Parse(x)).ToArray());
2. BLpop代码：
![image](https://github.com/2881099/FreeRedis/assets/102198415/29a7ec76-5551-43fd-93d6-2405ff2ae92a)
3. redis集群：
![image](https://github.com/2881099/FreeRedis/assets/102198415/9db1f658-7b32-4347-ae9a-c17e186b1ca3)

**Comment by 2881099** [comment]
使用 redis-cli 测试一下这个命令

**Comment by 2881099** [comment]
string BLPop(string key, int timeoutSeconds)

参数是秒，不是ms

值得注意，这里的参数值，不能大于 receiveTimeout=30000（注意连接串中的参数是ms）

**Comment by 2881099** [comment]
BLPop(key, 5)
