### ISSUE TITLE
主机使用Ipv6的域名是连接报错，使用Ipv6地址没有问题

### ISSUE THREAD

**Issue by hldstudy** [2881099/FreeRedis#190]
Redis连接失败：【xxx.xxxx.net]:10000/10】Status unavailable, waiting for recovery. 请求的名称有效，但是找不到请求的类型的数据。
使用[ipv6]:10000时正常连接

**Comment by 2881099** [comment]
域名目前都是解析成ipv4在链接，您可以debug一下源码
