### ISSUE TITLE
有计划支持OpenTelemetry吗

### ISSUE THREAD

**Issue by ZUOXIANGE** [2881099/FreeRedis#196]
参考 [OpenTelemetry.Instrumentation.StackExchangeRedis](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.StackExchangeRedis/README.md)

**Comment by 2881099** [comment]
使用 cli.Notice 事件可以处理一下消息格式

**Comment by ZUOXIANGE** [comment]
如果是通过cli.Notice自行实现的话,目前只能通过解析Log string获取参数,对于实现来说并不友好.可能还需要结合[文档](https://opentelemetry.io/docs/specs/semconv/database/redis/)讨论下需要支持哪些tag,然后确定在NoticeEventArgs里加上对应的参数

**Comment by 2881099** [comment]
https://github.com/2881099/FreeRedis/blob/master/src/FreeRedis/RedisClientEvents.cs

 
Notice 的实现参考，其实是一个拦截器。

**Comment by 2881099** [comment]
class NoticeCallInterceptor : IInterceptor

**Comment by ZUOXIANGE** [comment]
那好像可以直接在Before和After里直接实现,我空了写写看

**Comment by ZUOXIANGE** [comment]
我已经基本完成了相关代码,这是实现的trace效果图
![image](https://github.com/user-attachments/assets/ebeba8e9-cf64-47e7-81e9-6294284f2770)
但是我还没找到通过InterceptorBeforeEventArgs获取`db.namespace`,`server.address`,`server.port`,`network.peer.address`,`network.peer.port` 这几个参数的方法,可以给我点提示和指导吗

**Comment by 2881099** [comment]
InterceptorAfterEventArgs

这个参数更多，是执行之后才能确定向哪个 server 发送命令。

**Comment by ZUOXIANGE** [comment]
我现在用InterceptorAfterEventArgs解析[WriteTarget](https://github.com/2881099/FreeRedis/commit/a76cbd64a943bdbc205f5b85e836abfe25fd4e45)实现了,麻烦看看有没有什么其他的建议呢?没有的话我就提个PR

**Comment by 2881099** [comment]
放个链接到你的github仓储地址即可，属于扩展

**Comment by ZUOXIANGE** [comment]
要修改freeredis项目恐怕不行吧

**Comment by 2881099** [comment]
有哪些改动，需要评估

**Comment by ZUOXIANGE** [comment]
可以看看我这两个[提交](https://github.com/2881099/FreeRedis/compare/master...ZUOXIANGE:FreeRedis:master)

**Comment by 2881099** [comment]
问题不大，我主要担心在主仓库，未来有其他对接需求。

你提交吧，我邀请你进入项目的开发权限。

**Comment by ZUOXIANGE** [comment]
PR提了,需要合并,发布的话还需要发布新的nuget包

**Comment by 2881099** [comment]
明天发布nuget
