### ISSUE TITLE
出现了大量的域名链接超时。。

### ISSUE THREAD

**Issue by nodyang** [2881099/FreeRedis#210]
{"Success":false,"Message":"【redis.time.com:6399/0】Status unavailable, waiting for recovery. Connect to redis-server(redis.time.com:6399-> Unspecifiedredis.time.com:6399) timeout, DEBUG: Dns.GetHostEntry(redis.time.com)=System.Net.IPHostEntry"}
[ELAPSED] 并发量大的时候。接口大约停顿2分钟才回复正常

**Comment by nodyang** [comment]
现在有个最大的问题。卡死以后 程序大面积瘫痪。

**Comment by kasnti** [comment]
请问你是怎么解决的呢

**Comment by RobotJohns** [comment]
大佬怎么破的？ 我们也是 阿里云redis, 出现了同样的问题
