### ISSUE TITLE
DelayQueue 内部使用整数秒来作为zset的分数会导致延迟队列提前几百毫秒触发

### ISSUE THREAD

**Issue by xiaobaxiang** [2881099/FreeRedis#217]
DelayQueue 内部使用整数秒来作为zset的分数会导致延迟队列提前几百毫秒触发,建议使用毫秒或者浮点数表示分数

2024-12-27 14:08:42.664333---- Enter
2024-12-27 14:08:45.067739---- DelayQueue Trigger

![image](https://github.com/user-attachments/assets/356c032f-a9e9-4d22-919e-6e7f12db07d6)

**Comment by 2881099** [comment]
换成 TicksPerMillisecond 是否满足需求？

**Comment by 2881099** [comment]
源代码推上去了，有空检测一下

**Comment by xiaobaxiang** [comment]
满足需求，感谢大佬
