### ISSUE TITLE
XGroupCreateConsumer方法中XGROUP CREATECONSUMER命令不存在

### ISSUE THREAD

**Issue by Neddy1995** [2881099/FreeRedis#218]
stream创建消费者的命令为XGROUP CREATE <key> <groupname> <id or $> [opt] -- Create a new consumer group.

**Comment by 2881099** [comment]
你的 redis-server 是什么版本？

https://redis.io/docs/latest/commands/xgroup-createconsumer/

Available since: 6.2.0

**Comment by 2881099** [comment]
你的 redis-server 是什么版本？

https://redis.io/docs/latest/commands/xgroup-createconsumer/

Available since: 6.2.0

**Comment by 2881099** [comment]
XGROUP CREATE key group <id | $> [MKSTREAM]

Available since: 5.0.0
