### ISSUE TITLE
PR Process modification

### ISSUE THREAD

**Issue by tomatopunk** [2881099/FreeRedis#22]
我将进行一些关于PR流程以及组件的添加.

目的:
添加pr时,自动检测单元测试覆盖率与热力图bot.
添加对代码质量检测,以及一键创建Repository Issues.
添加对于net5.Ubuntu与Macos os版本执行单元测试.

**Comment by tomatopunk** [comment]
关于PR的Pipeline,我建议使用Azure.原因如下

dotnet环境在github action支持不好,Azure作为Microsoft的产品,在开源的CICD中支持是最好的.且对开源项目免费.
链接如下:[github marketplace](https://github.com/marketplace/azure-pipelines)

**Comment by tomatopunk** [comment]
我还建议添加[WIP组件](https://github.com/marketplace/wip),在PR的Title中添加`[WIP]`,阻断Merge以及PR的管道执行

**Comment by tomatopunk** [comment]
关于代码质量检测,目前比较严格的是[BetterCodeHub](https://github.com/marketplace/better-code-hub),本身提供commit级别的检测.对代码中的质量不佳的代码块,可以一键创建Issue,方便社区进行重构

**Comment by tomatopunk** [comment]
单元测试覆盖率与单元测试热力图,我建议使用[Codecov](https://github.com/marketplace/codecov).该组件可以对CI时成功的单元测试文档进行分析,将结果更新到PR中.
![Uploading image.png…]()

**Comment by tomatopunk** [comment]
对于基准仓库的组件添加,需要对基准仓库有写权限.请OWN记得配置一下.
我预计将更新的内容添加在/root/scripts./root/workflow.以及制定了项目级别的Nuget.Config

**Comment by NMSAzulX** [comment]
Pipeline 使用 Github 和 Azure 两种。  
WIP +1  
BetterCodeHub +1  
Codecov +1  
Nuget +1  预览版建议使用手动提交到 NCC 的 MyGet。

**Comment by tomatopunk** [comment]
> Pipeline 使用 Github 和 Azure 两种。
> WIP +1
> BetterCodeHub +1
> Codecov +1
> Nuget +1 预览版建议使用手动提交到 NCC 的 MyGet。

ok

**Comment by NMSAzulX** [comment]
@tomatopunk 哦还有协议扫描

**Comment by tomatopunk** [comment]
> @tomatopunk 哦还有协议扫描

协议扫描那就用fossa吧,例如[这个项目](https://github.com/fossas/fossa-cli-orb/pull/6).看下pr中是否添加了一个不符合我们协议的依赖.

**Comment by WeihanLi** [comment]
WIP, Github 现在不是可以直接把 PR 标记为草稿（Draft）了吗，Draft PR 不能被 Merge，功能是类似的吧
Github Actions 有什么 Azure Pipelines 没有的功能吗？

**Comment by tomatopunk** [comment]
> WIP, Github 现在不是可以直接把 PR 标记为草稿（Draft）了吗，Draft PR 不能被 Merge，功能是类似的吧
> Github Actions 有什么 Azure Pipelines 没有的功能吗？

WIP跟Github的Draft相比来说,前者出现的时间很早..

后者是最近Github才推出的功能..两者功能缺失类似,都可以对PullRuquest进行abort

从社区的角度而言,遵循大多数人的习惯是一个不错的想法..

其次从个人角度来说..我不是很喜欢Draft的功能..它实在是太隐蔽了....
![image](https://user-images.githubusercontent.com/40015047/100224709-2471d700-2f58-11eb-8a33-63c08a1464f0.png)

**Comment by tomatopunk** [comment]
> WIP, Github 现在不是可以直接把 PR 标记为草稿（Draft）了吗，Draft PR 不能被 Merge，功能是类似的吧
> Github Actions 有什么 Azure Pipelines 没有的功能吗？

其次是关于Azurepipe vs github actions

从我的角度而言,我更倾向于github action.因为对我们而言.在其他地方多一个账号,就需要多一份维护成本,以及增加我们自动化的复杂程度.

功能上来说,其实两者很类似.我已知,且常用的:azurepipe有手动执行ci的UI...而github需要手动调用一个restful风格的接口.

我倾向azurepipe的另外考虑是: 几乎所有的微软开源出来的项目组,包括clr,roslyn..使用的都是azurepipe作为pr的检查工具(我觉得有可能是出于并行度的考虑).

对于这种完全托管在其他人(如github or other)..一旦发现某个我们无法解决的bug,可能就需要将工作迁移到另外的地方去..

我们不应该长期的维护CI,除非我们整个项目都进行了非常大的更改,它应该是非常问题的.
