### ISSUE TITLE
对象的反序列报错

### ISSUE THREAD

**Issue by luoyigit** [2881099/FreeRedis#45]
![image](https://user-images.githubusercontent.com/13757293/106080928-f9238800-6152-11eb-956e-26755b4408f7.png)

**Comment by luoyigit** [comment]
redis.Set("a", new TestClass() { Name ="aa" });

            var result  = redis.Get<TestClass>("a");

**Comment by 2881099** [comment]
```c#
cli.Serialize = obj => JsonConvert.SerializeObject(obj);
cli.Deserialize = (json, type) => JsonConvert.DeserializeObject(json, type);
```

你没有设置序列化

**Comment by luoyigit** [comment]
哦，明白。谢谢！
