### ISSUE TITLE
RedisClient初始化失败

### ISSUE THREAD

**Issue by aion1998** [2881099/FreeRedis#56]
初始化代码如下（抄demo的）
![image](https://user-images.githubusercontent.com/19725014/112942894-5c399700-9163-11eb-9e84-b6b8be0611e4.png)

程序执行到这会直接出现连接失败
redis管理器连接正常：
![image](https://user-images.githubusercontent.com/19725014/112942985-7a06fc00-9163-11eb-842e-621ae80866d7.png)

**Comment by 2881099** [comment]
失败有什么提示
