### ISSUE TITLE
Set<T> 泛型存储数据错误

### ISSUE THREAD

**Issue by LingDian2019** [2881099/FreeRedis#59]
redisClientContext?.Set("WebAPI:AccessToken:wcs", accessTokenInfo, 100000);
存储后结果是

![98B5B6A1-C3F3-46b1-8AD9-547C79ECBFBA](https://user-images.githubusercontent.com/49890738/116215520-5642d000-a77a-11eb-950e-1244010f3bef.png)

**Comment by 2881099** [comment]
没有设置序列化

//cli.Serialize = obj => JsonConvert.SerializeObject(obj);
//cli.Deserialize = (json, type) => JsonConvert.DeserializeObject(json, type);

**Comment by LingDian2019** [comment]
有计划支持泛型序列化操作不。

**Comment by duyanming** [comment]
给个默认的序列化岂不更好

**Comment by 2881099** [comment]
@duyanming @LingDian2019 

默认序列化以来其他组件，现在 0 依赖更轻量，无论是 .net framework 还是 .net core 或者其他平台都可以引用。

**Comment by 564064202** [comment]
为什么不用二进制

**Comment by d617617** [comment]
原来如此，我认为此设计很棒，零依赖的原则无疑更加优秀。不过还是希望文档能写明

**Comment by 2881099** [comment]
谢谢认可，readme 示例代码有注释
