### ISSUE TITLE
sentinel模式下主从切换后，报连接异常错误

### ISSUE THREAD

**Issue by Dysheng** [2881099/FreeRedis#86]
测试条件：1 主（6380）、1从（6381） 、1 哨兵（26380）
步骤：
1、首先三个服务正常运行，运行测试代码，正常读写。
2、杀掉 主服务（6380），哨兵显示，原来的从服务（6381） 变为 主服务.
![40L2E$3IILG0DDUU~L9_)CP](https://user-images.githubusercontent.com/6174604/160580672-7934d30f-4d37-4121-aa58-cfe7cbd3aec3.png)

3、程序中从新 进行读写操作，报异常。
![{%I@OR8UF{XM%U@VY0VGACI](https://user-images.githubusercontent.com/6174604/160580977-12d57034-0f0e-415c-9125-ac5f7e83c46c.png)

代码：
![OK8TI7VW4G T9K{FZ6U30UX](https://user-images.githubusercontent.com/6174604/160581285-3dcae868-0e62-4fab-97de-2ec21ae61b5e.png)

读写操作：
![1648546397(1)](https://user-images.githubusercontent.com/6174604/160581386-0148eefd-aefb-4fe7-bf57-8ea07ebf48ec.png)

**Comment by 2881099** [comment]
其他问题：

- GetDatabase 不能这样使用，因为没有释放，正确参考 readme.md

**Comment by Dysheng** [comment]
> 其他问题：
> 
> * GetDatabase 不能这样使用，因为没有释放，正确参考 readme.md
去掉 getdatabase 後正常了。
